# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy SignalR Server

on:
  push:
    paths:
      - 'Chatter.Api/**'
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.103'

    - name: Build with dotnet
      run: dotnet build Chatter.Api/Chatter.Api.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish Chatter.Api/Chatter.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'chatterapi-dev-as'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_81f52d82fd814d0ebe6e20c752a19975 }}
        package: ${{env.DOTNET_ROOT}}/myapp 
